Project Phase/week-00/LandingPage/config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins

  devise_for :admins, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/index'
  get 'admin/addproject', as: :addproject
  get 'admin/addteam', as: :addteam
  get 'admin/addapprentice', as: :addapprentice
  get 'admin/index', as: :admin
  get 'teams/show'
  get 'admin/editproject'
  resources :projects
  resources :teams
  resources :admin
  resources :apprentices

  root :to => "home#index"
end

Project Phase/week-00/LandingPage/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

Project Phase/week-00/LandingPage/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Project Phase/week-00/LandingPage/app/models/apprentice.rb
class Apprentice < ApplicationRecord
	belongs_to :team
end

Project Phase/week-00/LandingPage/app/models/project.rb
class Project < ApplicationRecord
end

Project Phase/week-00/LandingPage/app/models/team.rb
class Team < ApplicationRecord
	extend Dragonfly::Model
	dragonfly_accessor :image
	has_many :apprentices
end

Project Phase/week-00/LandingPage/app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_admin!
  
  def login
  end

  def index
    @projects = Project.all
    @teams = Team.all
    @apprentices = Apprentice.all
  end

end

Project Phase/week-00/LandingPage/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def index
	end
	
end

Project Phase/week-00/LandingPage/app/controllers/apprentices_controller.rb
class ApprenticesController < ApplicationController

	before_action :authenticate_admin!

	def create
		@apprentice = Apprentice.new(apprentice_params)

		@apprentice.save
		redirect_to @apprentice
	end

	def edit
  		@apprentice = Apprentice.find(params[:id])
	end

	def update
	  @apprentice = Apprentice.find(params[:id])
	 
	  if @apprentice.update(apprentice_params)
	    redirect_to @apprentice
	  else
	    render 'edit'
	  end
	end

	def show
		@apprentice = Apprentice.find(params[:id])
				redirect_to :admin
	end

	def destroy
		@apprentice = Apprentice.find(params[:id])
		@apprentice.destroy
		redirect_to :admin
	end

	private

	def apprentice_params
		params.require(:apprentice).permit(:name, :github, :team_id)
	end

end

Project Phase/week-00/LandingPage/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@projects = Project.all
		@teams = Team.all
		@apprentices = Apprentice.all
	end

end

Project Phase/week-00/LandingPage/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :authenticate_admin!

	def create
		@project = Project.new(project_params)

		@project.save
		redirect_to @project
	end

	def edit
  		@project = Project.find(params[:id])
	end

	def update
	  @project = Project.find(params[:id])
	 
	  if @project.update(project_params)
	    redirect_to @project
	  else
	    render 'edit'
	  end
	end

	def show
		@project = Project.find(params[:id])
		redirect_to :admin
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to :admin
	end

	private

	def project_params
		params.require(:project).permit(:thumbnail_url, :title, :description)
	end

end

Project Phase/week-00/LandingPage/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	
	before_action :authenticate_admin!

	def edit
  		@team = Team.find(params[:id])
	end

	def update
	  @team = Team.find(params[:id])
	 
	  if @team.update(team_params)
	    redirect_to @team
	  else
	    render 'edit'
	  end
	end

	def show
		@team = Team.find(params[:id])
				redirect_to :admin
	end

	def destroy
		@team = Team.find(params[:id])
		@team.destroy
		redirect_to :admin
	end

	private

	def team_params
		params.require(:team).permit(:name, :image)
	end

end

Project Phase/week-00/LandingPage/app/helpers/admin_helper.rb
module AdminHelper
end

Project Phase/week-00/LandingPage/app/helpers/application_helper.rb
module ApplicationHelper
end

Project Phase/week-00/LandingPage/app/helpers/apprentices_helper.rb
module ApprenticesHelper
end

Project Phase/week-00/LandingPage/app/helpers/home_helper.rb
module HomeHelper
end

Project Phase/week-00/LandingPage/app/helpers/projects_helper.rb
module ProjectsHelper
end

Project Phase/week-00/LandingPage/app/helpers/teams_helper.rb
module TeamsHelper
end

Project Phase/week-00/LandingPage/app/views/admin/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', home_index_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'projects', '#projects', class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'teams', '#teams', class: "nav-link"%>
      </li>
    </ul>
  </div>
      <div class="mx-auto order-0">
        <%= link_to 'Admin', :admin, class: "btn btn-outline-dark"%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

Project Phase/week-00/LandingPage/app/views/admin/addapprentice.html.erb
<%= render 'admin_navbar'%>

<h4>Add New Apprentice:</h4>
<div>
<%= form_with scope: :apprentice, url: apprentices_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
    <p>
    <%= form.label :github %><br>
    <%= form.text_field :github %>
  </p>
  <p>
  <%= form.collection_select :team_id, Team.order(:name),:id,:name, include_blank: true %>
  </p>
  <p>
    <%= form.submit %>
  </p>
</div>
<% end %>

Project Phase/week-00/LandingPage/app/views/admin/addproject.html.erb
<%= render 'admin_navbar'%>

<h4>Add New Project:</h4>

<%= form_with scope: :project, url: projects_path, local: true do |form| %>
  <p>
    <%= form.label :thumbnail_url %><br>
    <%= form.text_field :thumbnail_url %>
  </p>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

Project Phase/week-00/LandingPage/app/views/admin/addteam.html.erb
<%= render 'admin_navbar'%>

<h4>Add New Team:</h4>
<div>
  <%= form_with scope: :team, url: teams_path, local: true do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.file_field :image %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>

Project Phase/week-00/LandingPage/app/views/admin/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Huli Landing Page</title>
</head>
<body>

<%= render 'admin_navbar'%>
<div class="pad">
	
	<%= link_to 'Add New Project', :addproject, class: "btn btn-success btn-lg"%> <br><br>
	<%= link_to 'Add New Team', :addteam, class: "btn btn-success btn-lg"%> <br><br>
	<%= link_to 'Add New Apprentice', :addapprentice, class: "btn btn-success btn-lg"%>
	<br>
	<br>
	<br>
	<h1 id="projects">Projects</h1>
	<br/>
	<br/>
	<% @projects.each do |project| %>
		<div>
			<%= image_tag project.thumbnail_url, id: "thumbnail" %>
			<h4><%= project.title %></h4>
			<%= link_to 'Edit', edit_project_path(project), class: "btn btn-outline-info btn-sm" %>
			<%= button_to "Remove", project_path(project), 
									method: :delete, 
									data: { confirm: "Are you sure you want to remove #{project.title}?" }, 
									class: 'btn btn-outline-danger btn-sm' %>
		</div>
	<br/>
	<br/>
	<% end %>
	<br/>
	<br/>
	<h1 id="teams">Teams</h1>
	<br/>
	<br/>
	<% @teams.each do |team| %>
			<div>
			<%= image_tag team.image.url, id: "teamimg-sm"%>
			
			<h2><%= team.name %></h2>
			</div>
	    <%= link_to 'Edit', edit_team_path(team), class: "btn btn-outline-info btn-sm" %>
	    <%= button_to "Remove", team_path(team), 
	    						method: :delete, 
								data: { confirm: "Are you sure you want to remove #{team.name}?" }, 
								class: 'btn btn-outline-danger btn-sm' %>
		<p>Team Members:</p>
	    <ul>
	    <% team.apprentices.each do |apprentice| %>
	    	<li><%= apprentice.name %></li>
	    	<%= link_to 'Edit', edit_apprentice_path(apprentice), class: "btn btn-outline-info btn-sm" %>
	    	<%= button_to "Remove", apprentice_path(apprentice), 
									method: :delete, 
									data: { confirm: "Are you sure you want to remove #{apprentice.name}?" }, 
									class: 'btn btn-outline-danger btn-sm' %>
	    <% end %>
	    </ul>
	<% end %>
	<br/>
	<br/>
	<h1 id="teams">Apprentices</h1>
	<br/>
	<br/>
	<% @apprentices.order(:name).each do |apprentice| %>
	<ul>
		<li>
			<div>
				Name: <%= apprentice.name %>
			</div>
			<div>
				Github: <%= apprentice.github %>
			</div>
			<div>
				Team: <%= Team.find(apprentice.team_id).name  %>
			</div>
		<%= link_to 'Edit', edit_apprentice_path(apprentice), class: "btn btn-outline-info btn-sm" %>
		<%= button_to "Remove", apprentice_path(apprentice), 
								method: :delete, data: { confirm: "Are you sure you want to remove #{apprentice.name}?"}, 
								class: 'btn btn-outline-danger btn-sm' %>
		</li>
	</ul>
	<% end %>
</div>
</body>
</html>

Project Phase/week-00/LandingPage/app/views/apprentices/edit.html.erb
<h1>Edit Apprentice</h1>
 
<%= form_with(model: @apprentice, local: true) do |form| %>
 
  <% if @apprentice.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@apprentice.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @apprentice.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :github %><br>
    <%= form.text_field :github %>
  </p>
    <%= form.collection_select :team_id, Team.order(:name),:id,:name, include_blank: true %>
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', :admin %>

Project Phase/week-00/LandingPage/app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Huli Landing Page</title>
</head>
<body>
<div id="jumbo">

<%= render 'shared/navbar'%>

	<div class="jumbotron jumbotron-fluid">
	  <div class="container">
	    <h1 class="display-4">狐狸</h1>
	    <h1 class="display-4">Welcome to the Húlí landing page!</h1>
	    <p class="lead">Here you can find an overview of the projects and teams at Húlí.</p>
	  </div>
	</div>
</div>

</div>
<div class="pad">
<h1 id="projects">Projects</h1>

<% @projects.each do |project| %>
<div class="container">
	<%= image_tag project.thumbnail_url.to_s, id: "thumbnail", class: "center" %>
	<h4><%= project.title %></h4>
	<p><%= project.description %></p>
</div>
<% end %>

<h1 id="teams">Teams</h1>
<% @teams.each do |team| %>
<br/>
<div class="team">
  <h2>Team <%= team.name %></h2>
  <%= image_tag team.image.url, id: "teamimg", class: "teamphoto"%>
  <p id="members">Team Members:</p>
  <ul>
  <% team.apprentices.each do |apprentice| %>
  	<li><div><%= link_to apprentice.name, apprentice.github, id: "github", target: "_blank" %></div></li>
  <% end %>
  </ul>
</div>
<br/>
<% end %>

</div>
</body>
</html>

Project Phase/week-00/LandingPage/app/views/shared/_lorem_ipsum.html.erb
<p>Lorem ipsum dolor sit amet, an cum admodum invidunt, feugiat vivendum assueverit ex vix. Vis stet clita commodo at, nam in legimus eleifend. Laoreet persecuti vim ad, ut est assum habemus docendi. His at facilis interpretaris, mucius sententiae ut eos, eligendi electram maluisset ei qui.

Diam viderer efficiendi pri ut, munere scripta persequeris ei ius. Cibo minimum ius ex. At epicurei salutandi sententiae vel. Eos no cibo ceteros expetenda, quo ei vidit erroribus disputationi. Eam adhuc pertinax efficiantur ea, et nullam alienum sea. Nec modo postea ea.

Pro ut aliquam epicurei. Meis simul ex mea, no mundi laudem incorrupte mel. Dolorem scaevola reformidans eam no, ea nam quaeque pericula facilisis. No mei solet option. Quot mentitum duo et. Debet commodo malorum ex vix, ei unum possim alterum nam, in vim aeterno diceret omnesque.

Alterum detraxit at has, mei hendrerit quaerendum ea. Congue decore noluisse eam ne, an nam fierent adipisci pertinax, an mei cibo maiorum expetendis. Cu pro ullum inani perfecto, mel commodo tamquam labores id. Ea integre legimus usu. Suscipit sadipscing ad vis. Molestie singulis an sit, his posidonium contentiones in.

Nec ea quidam debitis, meis percipit splendide an cum, nonumy soluta timeam in est. Eu volutpat argumentum honestatis pro. Democritum disputando appellantur id vix. Id inermis nostrum vim. Nostrum iudicabit cu sit, ne nec dicat conceptam.</p>

Project Phase/week-00/LandingPage/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'home', home_index_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'projects', '#projects', class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'teams', '#teams', class: "nav-link"%>
      </li>
    </ul>
  </div>
      <div class="mx-auto order-0">
        <%= link_to 'Admin', :admin, class: "btn btn-outline-dark"%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>